version: '3'

services:
  db:
    image: mysql:8.3
    container_name: wp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"

  wordpress:
    image: wordpress:6.4
    container_name: wordpress64
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: testdb
    depends_on:
      - db
